import { bibliotecaRepo } from "./repository"
import type { LibraryBook } from "./types"

export interface SeedBookEntry {
  title: string
  normalized_title: string
  author: string
  work_type: string
  series?: string
  volume_number?: number
  description: string
  summary: string
  status: "descubierto"
  privacy_level: "interno_eliana" | "comunidad" | "publico"
  tags: string[]
}

export const SEED_CATALOG: SeedBookEntry[] = [
  // ===== 01 — IDENTIDAD Y AUTOBIOGRAFÍA =====
  {
    title: "Yo Miguel Soria Martínez",
    normalized_title: "yo miguel soria martinez",
    author: "Miguel Soria Martínez",
    work_type: "autobiography",
    description: "Autobiografía oficial del fundador de MSM MY STORE LLC y creador del ecosistema ZAFIRO. Narra su trayectoria desde sus orígenes hasta la visión del futuro.",
    summary: "Autobiografía oficial del fundador de MSM MY STORE LLC.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["autobiografia", "identidad", "don-miguel", "historia"],
  },
  {
    title: "Perfil del Fundador",
    normalized_title: "perfil del fundador",
    author: "Miguel Soria Martínez",
    work_type: "profile",
    description: "Documento resumen de la trayectoria profesional, visión y valores de Miguel Soria Martínez como fundador de MSM MY STORE LLC.",
    summary: "Trayectoria profesional y visión del fundador.",
    status: "descubierto",
    privacy_level: "comunidad",
    tags: ["perfil", "fundador", "msm"],
  },
  {
    title: "Historias Personales",
    normalized_title: "historias personales",
    author: "Miguel Soria Martínez",
    work_type: "stories",
    description: "Compilación de relatos y vivencias personales de Miguel Soria Martínez que ilustran momentos clave de su vida y enseñanza.",
    summary: "Relatos y vivencias personales documentadas.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["historias", "vivencias", "personal"],
  },

  // ===== 02 — YO SOY Y PALABRA =====
  {
    title: "Yo soy: el poder del lenguaje positivo",
    normalized_title: "yo soy el poder del lenguaje positivo",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Yo Soy",
    description: "Obra fundamental del corpus del Yo Soy. Establece que la palabra 'Yo Soy' es una declaración de identidad y creación consciente que modela la realidad personal.",
    summary: "El 'Yo Soy' como herramienta de creación consciente.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["yo-soy", "lenguaje-positivo", "palabra-creadora", "libro-piloto"],
  },
  {
    title: "El Teléfono del Yo Soy",
    normalized_title: "el telefono del yo soy",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Yo Soy",
    description: "Desarrolla la metáfora del teléfono como canal de comunicación directa con el Yo Divino. Enseña cómo sintonizar la frecuencia divina y eliminar interferencias.",
    summary: "Canal de comunicación directa con el Yo Divino.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["yo-soy", "telefono", "comunicacion-divina", "libro-piloto"],
  },
  {
    title: "El Código Vivo del Yo Soy",
    normalized_title: "el codigo vivo del yo soy",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Yo Soy",
    description: "Expande los principios del Yo Soy en un sistema de reglas prácticas y activas para la transformación consciente de la realidad.",
    summary: "Principios activos del lenguaje como sistema de transformación.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["yo-soy", "codigo-vivo", "transformacion"],
  },
  {
    title: "Yo Soy: Palabra Creadora",
    normalized_title: "yo soy palabra creadora",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Yo Soy",
    description: "Desarrolla el aspecto creativo del lenguaje y la palabra como instrumento de creación consciente de realidad material y espiritual.",
    summary: "La palabra como instrumento de creación consciente.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["yo-soy", "palabra-creadora", "creacion"],
  },
  {
    title: "El Despertar del Yo Soy",
    normalized_title: "el despertar del yo soy",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Yo Soy",
    description: "Describe la transición de la conciencia dormida a la conciencia despierta del Ser a través del reconocimiento del poder del Yo Soy.",
    summary: "Transición hacia la conciencia despierta del Ser.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["yo-soy", "despertar", "conciencia"],
  },
  {
    title: "Evangelio del Yo Soy",
    normalized_title: "evangelio del yo soy",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Yo Soy",
    description: "Presenta las enseñanzas fundamentales del Yo Soy en formato de escritura sagrada contemporánea. Compilación de verdades espirituales fundamentales.",
    summary: "Enseñanzas fundamentales del Yo Soy en formato de escritura sagrada.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["yo-soy", "evangelio", "ensenanzas"],
  },

  // ===== 03 — FE Y ESPIRITUALIDAD =====
  {
    title: "La Fe como Fuerza Transformadora",
    normalized_title: "la fe como fuerza transformadora",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Fe y Espiritualidad",
    description: "Explora la fe activa como motor de cambio personal y social. La fe no como creencia pasiva sino como fuerza dinámica de transformación.",
    summary: "La fe activa como motor de cambio personal y social.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["fe", "transformacion", "espiritualidad"],
  },
  {
    title: "Cartas al Yo Divino",
    normalized_title: "cartas al yo divino",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Fe y Espiritualidad",
    description: "Correspondencia espiritual que modela la comunicación íntima y personal con Dios. Cada carta es un ejemplo de diálogo sincero con lo divino.",
    summary: "Correspondencia espiritual con lo divino.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["cartas", "yo-divino", "oracion"],
  },
  {
    title: "El Sistema Operativo del Cielo en la Tierra",
    normalized_title: "el sistema operativo del cielo en la tierra",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Fe y Espiritualidad",
    description: "Presenta principios celestiales aplicados a la vida terrenal. Un 'sistema operativo' espiritual para vivir en la tierra con la lógica del cielo.",
    summary: "Principios celestiales aplicados a la vida terrenal.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["sistema-operativo", "cielo", "tierra", "espiritualidad"],
  },
  {
    title: "El Sistema Operativo del Ser",
    normalized_title: "el sistema operativo del ser",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Fe y Espiritualidad",
    description: "Arquitectura interna del ser humano vista como un sistema operativo espiritual. Cómo programar y actualizar la identidad interior.",
    summary: "Arquitectura interna del ser humano como sistema operativo.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["sistema-operativo", "ser", "identidad"],
  },
  {
    title: "Hablándole al Espíritu Santo",
    normalized_title: "hablandole al espiritu santo",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Fe y Espiritualidad",
    description: "Diálogo y enseñanza sobre la relación personal con el Espíritu Santo, tercera persona de la Trinidad. Guía para la comunicación espiritual.",
    summary: "Relación y comunicación con el Espíritu Santo.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["espiritu-santo", "trinidad", "oracion"],
  },
  {
    title: "Jesús, la llave del universo",
    normalized_title: "jesus la llave del universo",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Fe y Espiritualidad",
    description: "Jesucristo como acceso a la comprensión total de la creación, el universo y el propósito divino. La clave que desbloquea todo conocimiento.",
    summary: "Cristo como acceso a la comprensión total de la creación.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["jesus", "llave", "universo", "cristo"],
  },
  {
    title: "Cantos del Espíritu",
    normalized_title: "cantos del espiritu",
    author: "Miguel Soria Martínez",
    work_type: "music",
    series: "Fe y Espiritualidad",
    description: "Expresiones musicales y poéticas de la vida espiritual. Himnos, alabanzas y canciones de elevación consciente.",
    summary: "Música y poesía de la vida espiritual.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["cantos", "musica", "himnos", "espiritu"],
  },

  // ===== 04 — SUEÑOS Y CONCIENCIA =====
  {
    title: "Los Sueños que Crean Realidades I",
    normalized_title: "los suenos que crean realidades i",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Los Sueños que Crean Realidades",
    volume_number: 1,
    description: "Primer tomo de la serie. Documenta sueños proféticos, visiones y enseñanzas recibidas durante el estado onírico. Postula que los sueños son semillas de realidades alternas.",
    summary: "Sueños proféticos y visiones documentados. Tomo I de V.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["suenos", "realidades", "profecia", "conciencia", "libro-piloto", "serie"],
  },
  {
    title: "Los Sueños que Crean Realidades II",
    normalized_title: "los suenos que crean realidades ii",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Los Sueños que Crean Realidades",
    volume_number: 2,
    description: "Segundo tomo de la serie. Expansión de la conciencia onírica con nuevos sueños y visiones documentadas.",
    summary: "Expansión de la conciencia onírica. Tomo II de V.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["suenos", "realidades", "conciencia", "serie"],
  },
  {
    title: "Los Sueños que Crean Realidades III",
    normalized_title: "los suenos que crean realidades iii",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Los Sueños que Crean Realidades",
    volume_number: 3,
    description: "Tercer tomo. Explora los sueños lúcidos y la co-creación consciente de realidades alternas durante el estado onírico.",
    summary: "Sueños lúcidos y co-creación. Tomo III de V.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["suenos", "lucidos", "co-creacion", "serie"],
  },
  {
    title: "Los Sueños que Crean Realidades IV",
    normalized_title: "los suenos que crean realidades iv",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Los Sueños que Crean Realidades",
    volume_number: 4,
    description: "Cuarto tomo. Visiones colectivas y sueños compartidos entre múltiples personas como evidencia de la realidad compartida.",
    summary: "Visiones colectivas y sueños compartidos. Tomo IV de V.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["suenos", "colectivos", "visiones", "serie"],
  },
  {
    title: "Los Sueños que Crean Realidades V",
    normalized_title: "los suenos que crean realidades v",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Los Sueños que Crean Realidades",
    volume_number: 5,
    description: "Quinto y último tomo. La unificación de realidades y la integración del mundo onírico con la vigilia en una sola conciencia.",
    summary: "Unificación de realidades. Tomo V de V.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["suenos", "unificacion", "conciencia", "serie"],
  },
  {
    title: "Otra Dimensión en el Ahora",
    normalized_title: "otra dimension en el ahora",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Sueños y Conciencia",
    description: "La multidimensionalidad del presente y cómo acceder a otras capas de realidad que coexisten en el momento actual.",
    summary: "Acceso a otras dimensiones en el presente.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["dimension", "ahora", "multidimensionalidad"],
  },
  {
    title: "El Consejo Invisible",
    normalized_title: "el consejo invisible",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Sueños y Conciencia",
    description: "Sabiduría colectiva de seres trascendentes que guían desde planos superiores. El consejo invisible como fuente de orientación.",
    summary: "Sabiduría colectiva de guías espirituales.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["consejo-invisible", "sabiduria", "guias"],
  },

  // ===== 05 — ABUNDANCIA Y MENTALIDAD =====
  {
    title: "Yo Soy Riqueza",
    normalized_title: "yo soy riqueza",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Abundancia y Mentalidad",
    description: "La identidad de prosperidad como declaración consciente del Ser. La riqueza comienza con la declaración 'Yo Soy Riqueza'.",
    summary: "La identidad de prosperidad como declaración del Ser.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["riqueza", "abundancia", "yo-soy", "prosperidad"],
  },
  {
    title: "Los Millonarios",
    normalized_title: "los millonarios",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Abundancia y Mentalidad",
    description: "Principios y hábitos de los creadores de riqueza. Lecciones prácticas basadas en el estudio de mentalidades millonarias.",
    summary: "Principios y hábitos de creadores de riqueza.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["millonarios", "riqueza", "mentalidad", "habitos"],
  },
  {
    title: "Riqueza Infinita",
    normalized_title: "riqueza infinita",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Abundancia y Mentalidad",
    description: "El concepto de abundancia sin límites en todas las áreas de la vida. La riqueza verdadera es multidimensional.",
    summary: "Abundancia sin límites en todas las áreas.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["riqueza-infinita", "abundancia", "multidimensional"],
  },
  {
    title: "El Poder de Crear tu Realidad",
    normalized_title: "el poder de crear tu realidad",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Abundancia y Mentalidad",
    description: "Co-creación consciente de la realidad personal a través del pensamiento, la palabra y la acción alineada con el propósito divino.",
    summary: "Co-creación consciente de la realidad personal.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["crear-realidad", "co-creacion", "poder-personal"],
  },

  // ===== 06 — FAMILIA E HISTORIAS =====
  {
    title: "El Jardín de las Visualizaciones",
    normalized_title: "el jardin de las visualizaciones",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Familia e Historias",
    description: "Técnica de visualización familiar para la creación consciente. El jardín como metáfora del espacio interior donde cultivar realidades.",
    summary: "Técnica de visualización para la creación consciente familiar.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["visualizacion", "jardin", "familia", "creacion"],
  },
  {
    title: "La Noche que Sentí su Espíritu",
    normalized_title: "la noche que senti su espiritu",
    author: "Miguel Soria Martínez",
    work_type: "story",
    series: "Familia e Historias",
    description: "Experiencia espiritual de conexión con un ser querido fallecido. Relato personal de una noche de profunda conexión espiritual familiar.",
    summary: "Experiencia de conexión espiritual con un ser querido.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["espiritu", "conexion", "familia", "experiencia"],
  },
  {
    title: "Viviendo eternamente aquí en la Tierra",
    normalized_title: "viviendo eternamente aqui en la tierra",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Familia e Historias",
    description: "Reflexión sobre la vida eterna en el presente. Cómo experimentar la eternidad no después de la muerte sino en el aquí y ahora.",
    summary: "La vida eterna experimentada en el presente.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["eternidad", "tierra", "presente", "immortalidad"],
  },

  // ===== 07 — CIENCIA, TECNOLOGÍA Y FUTURO =====
  {
    title: "La Máquina del Futuro",
    normalized_title: "la maquina del futuro",
    author: "Miguel Soria Martínez",
    work_type: "technical",
    series: "Ciencia y Tecnología",
    description: "Documento técnico-visionario que detalla un dispositivo capaz de acceder, visualizar e interactuar con líneas temporales alternas y futuras. Combina física cuántica y conciencia.",
    summary: "Proyecto de invención tecnológica para navegación temporal.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["maquina-futuro", "invento", "tecnologia", "cuantico", "libro-piloto"],
  },
  {
    title: "El Puente de las Civilizaciones",
    normalized_title: "el puente de las civilizaciones",
    author: "Miguel Soria Martínez",
    work_type: "technical",
    series: "Ciencia y Tecnología",
    description: "Infraestructura conceptual que conecta eras y conocimientos. El puente como metáfora y proyecto para unir civilizaciones a través del tiempo.",
    summary: "Conexión entre eras y civilizaciones.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["puente", "civilizaciones", "conexion", "eras"],
  },
  {
    title: "El Universo Cuántico y Divino",
    normalized_title: "el universo cuantico y divino",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Ciencia y Tecnología",
    description: "Unificación de la física cuántica con la espiritualidad. Un modelo donde la ciencia y la fe no son opuestas sino complementarias.",
    summary: "Unificación de física cuántica y espiritualidad.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["universo", "cuantico", "divino", "ciencia", "espiritualidad"],
  },
  {
    title: "Ficha Técnica de ZAFIRO",
    normalized_title: "ficha tecnica de zafiro",
    author: "Miguel Soria Martínez",
    work_type: "technical",
    series: "Ciencia y Tecnología",
    description: "Especificaciones oficiales, arquitectura y documentación técnica de la plataforma ZAFIRO, la red social del conocimiento impulsada por IA.",
    summary: "Especificaciones técnicas de la plataforma ZAFIRO.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["zafiro", "tecnico", "arquitectura", "especificaciones"],
  },

  // ===== 08 — MSM Y EMPRENDIMIENTO =====
  {
    title: "Libro de msmmystore.com",
    normalized_title: "libro de msmmystore com",
    author: "Miguel Soria Martínez",
    work_type: "manual",
    series: "MSM y Emprendimiento",
    description: "Manual completo del ecosistema MSM: sus componentes, funcionamiento, visión empresarial y guía práctica para navegar la plataforma.",
    summary: "Manual completo del ecosistema MSM.",
    status: "descubierto",
    privacy_level: "comunidad",
    tags: ["msm", "manual", "ecosistema", "emprendimiento"],
  },
  {
    title: "MSM Mente Maestra",
    normalized_title: "msm mente maestra",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "MSM y Emprendimiento",
    description: "Inteligencia colectiva empresarial y red de conocimiento colaborativo. Sistema donde la comunidad entera contribuye al conocimiento compartido.",
    summary: "Inteligencia colectiva empresarial del ecosistema MSM.",
    status: "descubierto",
    privacy_level: "comunidad",
    tags: ["mente-maestra", "inteligencia-colectiva", "msm"],
  },

  // ===== 09 — ELEVACIÓN CONSCIENTE =====
  {
    title: "Enseñanzas",
    normalized_title: "ensenanzas",
    author: "Miguel Soria Martínez",
    work_type: "teachings",
    series: "Elevación Consciente",
    description: "Compilación de lecciones de vida extraídas de la experiencia, la reflexión y la guía espiritual de Miguel Soria Martínez.",
    summary: "Lecciones de vida y guía espiritual.",
    status: "descubierto",
    privacy_level: "comunidad",
    tags: ["ensenanzas", "lecciones", "sabiduria"],
  },
  {
    title: "Oraciones",
    normalized_title: "oraciones",
    author: "Miguel Soria Martínez",
    work_type: "prayers",
    series: "Elevación Consciente",
    description: "Compilación de oraciones y comunicaciones con lo divino compuestas por Miguel Soria Martínez.",
    summary: "Oraciones de comunicación con lo divino.",
    status: "descubierto",
    privacy_level: "comunidad",
    tags: ["oraciones", "divino", "comunicacion"],
  },
  {
    title: "Reflexiones",
    normalized_title: "reflexiones",
    author: "Miguel Soria Martínez",
    work_type: "reflections",
    series: "Elevación Consciente",
    description: "Meditaciones sobre la existencia, la naturaleza, el propósito de la vida y el camino espiritual.",
    summary: "Meditaciones sobre la existencia y el propósito.",
    status: "descubierto",
    privacy_level: "comunidad",
    tags: ["reflexiones", "meditacion", "existencia"],
  },

  // ===== 10 — GUIONES Y OBRAS CREATIVAS =====
  {
    title: "Tiempo 00:00",
    normalized_title: "tiempo 00 00",
    author: "Miguel Soria Martínez",
    work_type: "script",
    series: "Guiones y Obras Creativas",
    description: "Guion cinematográfico que explora el concepto del tiempo cero, el momento de creación y reinicio del universo.",
    summary: "Guion cinematográfico sobre el tiempo de creación.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["guion", "pelicula", "tiempo", "creacion"],
  },
  {
    title: "Cómo ser tu propio maestro: El poder cuántico de la voz",
    normalized_title: "como ser tu propio maestro el poder cuantico de la voz",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Elevación Consciente",
    description: "Enseñanza sobre el poder de la voz como instrumento cuántico de creación y transformación. Cómo ser tu propio guía a través del sonido y la palabra hablada.",
    summary: "El poder cuántico de la voz como instrumento de transformación.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["voz", "cuantico", "maestro", "ensenanza"],
  },
  {
    title: "La fe como fuerza transformadora",
    normalized_title: "la fe como fuerza transformadora",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Fe y Espiritualidad",
    description: "La fe activa como motor de cambio personal y social. Versión completa del libro sobre el poder transformador de la fe.",
    summary: "El poder transformador de la fe activa.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["fe", "transformacion", "poder"],
  },
  {
    title: "El Todo es Uno",
    normalized_title: "el todo es uno",
    author: "Miguel Soria Martínez",
    work_type: "book",
    series: "Ciencia y Tecnología",
    description: "Visión unificada de la realidad donde todo está interconectado. El principio de unidad como base del universo y la conciencia.",
    summary: "La unidad fundamental de toda la realidad.",
    status: "descubierto",
    privacy_level: "interno_eliana",
    tags: ["unidad", "todo", "uno", "conexion"],
  },
]

export async function seedLibraryCatalog(): Promise<{
  success: boolean
  books_created: number
  errors: string[]
}> {
  let booksCreated = 0
  const errors: string[] = []

  for (const entry of SEED_CATALOG) {
    try {
      const existing = await bibliotecaRepo.searchBooks({ query: entry.normalized_title, limit: 1 })
      const alreadyExists = existing.some(r =>
        r.book.normalized_title === entry.normalized_title || r.book.title === entry.title
      )

      if (alreadyExists) {
        continue
      }

      const book = await bibliotecaRepo.createBook({
        title: entry.title,
        normalized_title: entry.normalized_title,
        author: entry.author,
        work_type: entry.work_type,
        series: entry.series,
        volume_number: entry.volume_number,
        description: entry.description,
        summary: entry.summary,
        status: entry.status,
        privacy_level: entry.privacy_level,
        tags: entry.tags,
      } satisfies Partial<LibraryBook>)

      if (book) {
        booksCreated++
      } else {
        errors.push(`Failed to create: ${entry.title}`)
      }
    } catch (error) {
      errors.push(`Error creating ${entry.title}: ${error}`)
    }
  }

  return { success: errors.length === 0, books_created: booksCreated, errors }
}
